// <auto-generated />
using System;
using Gestion.Parc.Informatique.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion.Parc.Informatique.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20230525214303_addModels")]
    partial class addModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Equipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualPositionDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActualPositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarqueDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarqueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesurmentUnite")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldPositionDisplay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OldPositionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReformeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeConsommation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Marque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Personne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b7237a9-a500-4819-ae58-e393edfb561e"),
                            Age = 1,
                            CreationTimeUtc = new DateTime(2023, 5, 25, 21, 43, 2, 415, DateTimeKind.Utc).AddTicks(381),
                            IsDeleted = false,
                            Nom = "Djehinet",
                            Order = 0,
                            Prenom = "Djawed"
                        },
                        new
                        {
                            Id = new Guid("5669c63a-9bac-4928-9019-f9e3d59bfd1f"),
                            Age = 32,
                            CreationTimeUtc = new DateTime(2023, 5, 25, 21, 43, 2, 415, DateTimeKind.Utc).AddTicks(431),
                            IsDeleted = false,
                            Nom = "Djehinet",
                            Order = 0,
                            Prenom = "Nadjib"
                        },
                        new
                        {
                            Id = new Guid("ca5690d9-01e4-4267-b555-7b2f59570380"),
                            Age = 30,
                            CreationTimeUtc = new DateTime(2023, 5, 25, 21, 43, 2, 415, DateTimeKind.Utc).AddTicks(436),
                            IsDeleted = false,
                            Nom = "Djehinet",
                            Order = 0,
                            Prenom = "Fateh"
                        });
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructureChildren")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Structure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentStructureId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Data.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayFr")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ordre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Gestion.Parc.Informatique.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "djawed",
                            LastName = "djehinet",
                            PasswordHash = "$2a$11$EYjFiD/mUA9eCtNuS6O.du.ezBbIIaq1WQqUydaA8tmX/cC5bDVFK",
                            Username = "djawed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
